### PR TITLE
Added margin between slack invite container and footer

### PR DESCRIPTION
**Pull request by Fixy250185**
Resolution for issue #14

### CODE REVIEW

**Comment by verde79** [comment]
Brilliant, do you fancy changing the colour of the input field to white too and perhaps adding a "your.email.here.@email.com" type thing default text?!  Doesn't have to be done in this PR though

**Comment by verde79** [comment]
Cool, like the hover effect.  I've updated the invite url.  What do you think about doing away with the grey background altogether? Or changing to a different colour

**Comment by Fixy250185** [comment]
We could experiment with some colours. The blue seems nice so might try that

**Comment by verde79** [comment]
It's a very pale teal, nice and fresh though, I was thinking of maybe having the h4 titles in a darker teal background.  Nice to see I'm not the only sad person up at this time!

**Comment by Fixy250185** [comment]
I was working on my portfolio site and thought I'd take a break to work on this lol. I've got a branch on my local machine where I've changed the header and slack invite background colours to some various shades and tints of the same teal colour. I'll push it after the next commit is made to master.

**Pull request merged**
